# Generated by Django 3.2.7 on 2025-09-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
