# Generated by Django 3.2.7 on 2025-09-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('sourceType', models.CharField(max_length=30)),
                ('source_id', models.CharField(max_length=30)),
                ('isFlagged', models.BooleanField(default=False)),
                ('severityLevel', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('detectedLabels', models.CharField(blank=True, max_length=225, null=True)),
                ('analysisTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmojiAnalysis',
            fields=[
                ('emoji_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=30)),
                ('meaning', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('filePath', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cyber.user')),
            ],
        ),
        migrations.CreateModel(
            name='SlangInterpretation',
            fields=[
                ('slang_id', models.AutoField(primary_key=True, serialize=False)),
                ('slangText', models.CharField(max_length=30)),
                ('meaning', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cyber.user')),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('ocr_id', models.AutoField(primary_key=True, serialize=False)),
                ('extractedText', models.CharField(max_length=100)),
                ('extractionTime', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cyber.imagecontent')),
            ],
        ),
    ]
