# Generated by Django 3.2.7 on 2025-09-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber', '0005_contentanalysis_emojianalysis_imagecontent_ocrresult_slanginterpretation_textcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('activityType', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cyber.user')),
            ],
            options={
                'ordering': ['-timeStamp'],
            },
        ),
    ]
